version: '3.7'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # Puerto donde Localstack escucha
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
