FROM python:3.10.9-slim

RUN pip install -U pip & pip install pipenv

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy

COPY [ "batch_processing.py", "batch_processing.py" ]
COPY [ "model.bin", "model.bin" ]

ENTRYPOINT [ "python", "batch_processing.py" ]